### ISSUE TITLE
Mbed client and web server connection is very unreliable

### ISSUE THREAD

**Issue by ernotormikoski** [ARMmbed/mbed-client-linux-example#15] opened 2015-10-21 14:44 UTC
It was very hard to get Mbed client and web server connection work together and seems that it goes broken very easily.  In success full case Resource Value can be seen in server but then the next  attempt to connect and register may fail. I tried to change settings from NAT Firewall to Bridged in Virtual machine different ways and start client and server with different combinations.

x86-linux-native/source$ ./mbed-client-linux-example

**************** unsuccessful connection *************
Endpoint Name : a2c60630-7661-4a83-8c3a-67a7d16fefc2

Interface created
register object created
Device object created !!
Registering endpoint

Error occured Error Code : 6
Error occured Error Code : 6
Registered
Error occured Error Code : 6
Error occured Error Code : 6
Incrementing Resource Value
Resource Value /Test/0/D : 1
Error occured Error Code : 6
Error occured Error Code : 6
Unregistering endpoint and EXITING Program
Error occured Error Code : 10

**************** successful connection *************
Endpoint Name : a2c60630-7661-4a83-8c3a-67a7d16fefc2

Interface created
register object created
Device object created !!
Registering endpoint

Registered
Incrementing Resource Value
Resource Value /Test/0/D : 1
Sending update register

registration updated
Incrementing Resource Value
Resource Value /Test/0/D : 2
Incrementing Resource Value
Resource Value /Test/0/D : 3
Sending update register

registration updated
Incrementing Resource Value
Resource Value /Test/0/D : 4
Incrementing Resource Value
Resource Value /Test/0/D : 5
Sending update register

**Comment by ernotormikoski** [comment] 2015-10-21 14:44
@yogpan01 New issue for you

**Comment by simonqhughes** [comment] 2015-10-21 18:59
ARM Internal Ref: IOTCLT-371

**Comment by ernotormikoski** [comment] 2015-10-22 09:48
@yogpan01 I took latest updates from GitHub and now error case seems to give more information:

Endpoint Name : a2c60630-7661-4a83-8c3a-67a7d16fefc2

Interface created
register object created
Device object created !!
Registering endpoint

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError

Registered

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError
Incrementing Resource Value
Resource Value /Test/0/D : 1

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError
Sending update register

Error occured  : M2MInterface::NotAllowed
Incrementing Resource Value
Resource Value /Test/0/D : 2
Incrementing Resource Value
Resource Value /Test/0/D : 3

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError
Sending update register

Error occured  : M2MInterface::NotAllowed
Incrementing Resource Value
Resource Value /Test/0/D : 4
Incrementing Resource Value
Resource Value /Test/0/D : 5

**Comment by yogpan01** [comment] 2015-10-22 10:34
Interesting logs. I wonder why there is issue with network connectivity in your system. It seems that the connection is not very stable and UDP packets are not going through. There is a recommendation that your UDP port of 5684 should be open but I am suspecting some other issue. Would be worth looking at it.

**Comment by hasnainvirk** [comment] 2015-10-28 16:25
Also, until you clear cookies from Device Connector, it shows a connected device even when you have terminated the connection.

**Comment by ernotormikoski** [comment] 2015-10-29 07:12
Now this client seems to work, no errors anymore.

Endpoint Name : 21551027-83b1-495b-a9f0-92202bb0cffd

Interface created
register object created
Device object created !!
Registering endpoint

Registered
Incrementing Resource Value
Resource Value /Test/0/D : 1
Sending update register

registration updated
Incrementing Resource Value
Resource Value /Test/0/D : 2
Incrementing Resource Value
Resource Value /Test/0/D : 3
Sending update register

**Comment by yogpan01** [comment] 2015-10-29 14:04
Closing this issue.

**Closed by yogpan01** 2015-10-29 14:04 UTC
Labels: mirrored

**Comment by wosayttn** [comment] 2016-01-11 05:58
I encountered the such issue on my UBUNTU x64 Linux PC and ARM9 platform.
How to solve?

./mbed-client-linux-example/build/x86-linux-native/source/mbed-client-linux-example
Endpoint Name : db9293aa-e63c-4c69-bd3c-34bfbd856ad8

Interface created
register object created
Device object created !!
Registering endpoint

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError

Registered
Incrementing Resource Value
Resource Value /Test/0/D : 1
Sending update register

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError
Incrementing Resource Value
Resource Value /Test/0/D : 2

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError

Error occured  : M2MInterface::NetworkError
Incrementing Resource Value
Resource Value /Test/0/D : 3

**Comment by yogpan01** [comment] 2016-01-11 06:44
Hi, I believe you are using UDP connection type. Can you please send the wireshark logs ? This might be some network issue occuring occasionally.

**Comment by wosayttn** [comment] 2016-01-14 03:46
Hi, I just run the example code. It's over UDP by default. After changing to TCP, it seems more stable than UDP. My location is Taiwan. Where is the MDS server location? The issue is caused by UDP packet lose, right?

**Comment by yogpan01** [comment] 2016-01-14 06:40
Hi, the issue is most probably due to DTLS handshake packets coming in wrong order(in UDP) , this is more streamlined in TCP as it ensured packets arrive in right order. We are investigating this issue as to how to resolve the problem for UDP. The server is deployed in Cloud solution.
