### ISSUE TITLE
'yotta build mbed-client-linux-example' fails

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux-example#38] opened 2016-03-31 21:44 UTC
I have cloned the latest mbed-client-linux-example (commid id ac2b22d8faabcaf93c6f060707b3b2529374873f) and tried to build it using the command 'yt build mbed-client-linux-example'. This results in the error in the attachment below. Is it not allowed to specify the module name in the 'yt build' command anymore if we do not want to build the tests? This used to work when I previously built the example.

[error.txt](https://github.com/ARMmbed/mbed-client-linux-example/files/198630/error.txt)

**Comment by ciarmcom** [comment] 2016-03-31 23:50
ARM Internal Ref: IOTCLT-664

**Comment by teetak01** [comment] 2016-04-01 06:22
Hi Vanti, "yt build" should build the example without any tests. That is how it should be used. Is this building correctly for you?

yt build mbed-client-linux-example will also try building all the unit tests for the application. This will fail currently due to test-dependencies on component (cpputest) which is not yet public. Sorry about this. This is a known issue and we are working on this.

**Comment by vanti** [comment] 2016-04-01 17:00
Hi teetak01, according to the yotta documentation for 'yt build': "If no name arguments are specified then the **current module's tests will be built**, but not the tests for any other module.", and the description of the name argument: "name ...: one or more modules may be specified, in which case only these modules and their dependencies will be built. Use all_tests to cause all tests to be built.", my understanding is that not all tests would be built if a name is specified.

So I typically specify the module name when I do not want tests to be built. It turns out mbed-client-linux-example does not have a test directory, but still I'd have expected 'yt build mbed-client-linux-example' to work.

'yt build' does work for me, but just wanted to report this in case you were not aware.

**Comment by teetak01** [comment] 2016-04-02 06:04
Hi Vanti, I much appriciate that you raised a ticket on this issue. You are quite right on how yotta should work. The problem is that we have a broken dependency chain, which we will resolve soon. So, even though 'yt build mbed-client-linux-example' is not building any tests from dependencies, it will STILL try to download all the testDependencies for all modules. Because one of those dependencies is private, yotta will fail.

So definitely what you reported is a real issue on our side and will be resolved promptly. I will update this ticket when we make progress on this issue.

**Comment by teetak01** [comment] 2016-04-04 12:25
Hi Vanti, the issue should be resolved now. Just run "yotta update" and you should be able to build with "yt build mbed-client-linux-example"

**Comment by teetak01** [comment] 2016-04-05 06:56
Closing this ticket now as the issue should be resolved now. If you still observe any problems, please comment either on this ticket or raise a new one. Thank you again for reporting the issue.

**Closed by teetak01** 2016-04-05 06:56 UTC
Labels: mirrored
